import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  // `src/bindings` is generated by `cargo test` (overview.md 6.8) and `.venv*` by
  // `scripts/export_clap_onnx.py` -- neither is source, and the venv holds enough vendored
  // JavaScript to make a lint run fail on files nobody in this repository wrote.
  // `dist-profile` is the Phase 7 measurement harness's bundle and `build` holds the
  // compiled WKWebView runner; both are output, like `dist`.
  { ignores: ['dist', 'dist-profile', 'build', 'src-tauri', 'src/bindings', '.venv*'] },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  reactHooks.configs.flat['recommended-latest'],
  prettier,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    files: ['*.config.{js,ts}'],
    languageOptions: { globals: globals.node },
    extends: [tseslint.configs.disableTypeChecked],
  },
  // Standalone Node scripts. Linted, but not type-checked: they are deliberately outside
  // the app's `tsconfig`, because a measurement harness that needed the app's toolchain to
  // run would stop being usable the moment the toolchain broke.
  {
    files: ['scripts/**/*.{js,mjs}'],
    languageOptions: { globals: globals.node },
    extends: [tseslint.configs.disableTypeChecked],
  },
);
