// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything that can cross the IPC boundary as a failure.
 *
 * `#[serde(tag = "kind", content = "detail")]` makes this a TypeScript discriminated union:
 * `{ kind: "modelMissing" }`, `{ kind: "decode", detail: { path, reason } }`. The frontend
 * switches on `kind` and renders a recovery action per case.
 */
export type AppError = { "kind": "modelMissing" } | { "kind": "modelDownload", "detail": { message: string, resumable: boolean, } } | { "kind": "checksumMismatch", "detail": { expected: string, got: string, } } | { "kind": "modelUnpinned", "detail": { version: string, } } | { "kind": "database", "detail": string } | { "kind": "decode", "detail": { path: string, reason: string, } } | { "kind": "notFound", "detail": string } | { "kind": "scanInProgress", "detail": { scanId: number, } } | { "kind": "refitInProgress", "detail": { jobId: number, } } | { "kind": "cancelled" } | { "kind": "noProjection" } | { "kind": "tooFewSamples", "detail": { operation: string, have: number, need: number, } } | { "kind": "invalidArgument", "detail": { field: string, reason: string, } } | { "kind": "unavailable", "detail": { feature: string, } } | { "kind": "internal", "detail": string };
