// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The settings that survive a restart (`task.md` Phase 9). Everything else Settings shows --
 * model status, projection params -- is either derived or lives on its own durable row
 * already, and does not belong in this key/value store.
 */
export type AppSettings = { 
/**
 * `None` means "the OS default," which is also the initial state before anyone has
 * chosen a device.
 */
audioDevice: string | null, gain: number, };
