// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One output device the Settings panel can offer.
 */
export type AudioDeviceInfo = { name: string, isDefault: boolean, };
