// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionMember } from "./CollectionMember";

/**
 * A collection with its members, in the order the user arranged them.
 *
 * A DTO distinct from [`Collection`] rather than an optional field on it: the collection
 * list only ever needs a name and a count, and fetching every member of every collection to
 * answer `list_collections` would be a query nobody asked for.
 */
export type CollectionDetail = { id: number, name: string, createdAt: number, members: Array<CollectionMember>, };
