// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One sample inside a collection, in display order (`overview.md` §6.1, Phase 9).
 */
export type CollectionMember = { sampleId: number, relPath: string, filename: string, durationMs: number | null, };
