// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A saved set of samples.
 */
export type Collection = { id: number, name: string, createdAt: number, sampleCount: number, };
