// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * The terminal event of a download.
 */
export type DownloadFinished = { 
/**
 * Where the verified model landed, on success.
 */
path: string | null, error: AppError | null, };
