// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadFinished } from "./DownloadFinished";
import type { DownloadProgressEvent } from "./DownloadProgressEvent";

/**
 * What the model download streams back (`overview.md` §3.5).
 */
export type DownloadEvent = { "event": "progress" } & DownloadProgressEvent | { "event": "finished" } & DownloadFinished;
