// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bytes so far, and the total when the server admits to one.
 *
 * `total` is `None` for a chunked response, and the first-run screen has to render that
 * as a live byte count rather than a bar stuck at zero -- which is why it is an `Option`
 * on the wire and not a hopeful guess made in Rust.
 */
export type DownloadProgressEvent = { downloaded: number, total: number | null, };
