// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which scalar a feature column or a range filter is about.
 *
 * An enum rather than a column name on the wire, for the obvious reason: a string that
 * reaches a `SELECT` is an injection, and a string that reaches a `SELECT` through a
 * `format!` is the injection. [`Feature::column`] is the only mapping from this to SQL and
 * it returns a `&'static str` picked from a `match`, so no caller-supplied text ever
 * becomes part of a statement.
 */
export type Feature = "peakDb" | "rmsDb" | "lufsIntegrated" | "spectralCentroid" | "spectralFlatness" | "zeroCrossing" | "onsetDensity" | "bpm" | "bpmConfidence" | "keyRoot" | "keyMode" | "keyConfidence" | "durationMs";
