// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Feature } from "./Feature";

/**
 * An inclusive range with either end optional. `{ min: 100 }` is "at least 100".
 */
export type FeatureRange = { feature: Feature, min?: number, max?: number, };
