// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A library root as the UI shows it.
 */
export type LibraryRoot = { id: number, path: string, label: string | null, enabled: boolean, addedAt: number, 
/**
 * Rows currently under this root. The number the sidebar shows next to the folder, and
 * the reason this is a DTO: `queries::LibraryRoot` is one table and this is two.
 */
sampleCount: number, };
