// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The three states of [`crate::model::ModelStatus`], as a TypeScript union.
 */
export type ModelState = "installed" | "downloadable" | "unpinned";
