// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelState } from "./ModelState";

/**
 * What `get_model_status` reports, without touching the network or the graph.
 */
export type ModelStatus = { 
/**
 * Model version, independent of the app's.
 */
version: string, state: ModelState, 
/**
 * Where an installed model lives, or would.
 */
path: string, 
/**
 * Size of the published asset, when the release records one.
 */
totalBytes: number | null, 
/**
 * Bytes already on disk in the `.partial`, so a first-run screen can offer "Resume"
 * with a number on it rather than "Download" for the third time.
 */
downloadedBytes: number | null, 
/**
 * Whether the `ort` session has been built. Reported, never *caused*: cold start is
 * budgeted at under two seconds excluding session init (`overview.md` §7), and a
 * status call that forced the session would spend that budget on a progress badge.
 */
sessionReady: boolean, };
