// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of a nearest-neighbor listing.
 */
export type Neighbor = { sampleId: number, relPath: string, filename: string, durationMs: number | null, 
/**
 * Cosine similarity of the two sounds' standardized feature vectors, floored at 0 for
 * display.
 */
similarity: number, };
