// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of a nearest-neighbor listing.
 */
export type Neighbor = { sampleId: number, relPath: string, filename: string, durationMs: number | null, 
/**
 * Cosine similarity in `[-1, 1]`. Every stored vector is L2-normalized, so this is a
 * dot product.
 */
similarity: number, };
