// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeatureRange } from "./FeatureRange";

/**
 * What `query_samples` filters on (`overview.md` §6.1).
 *
 * Every field is optional and an omitted field is not a constraint, so `{}` matches the
 * whole library. Populated fields are combined with AND -- a filter panel where ticking a
 * second box widened the result would be a filter panel nobody could reason about.
 */
export type QueryFilter = { 
/**
 * FTS5 query over filename and tags. Passed through as written, so `KICK*` and
 * `808 NOT snare` work. A malformed query is a typed error, not a panic.
 */
text?: string, 
/**
 * Empty means every root.
 */
rootIds: Array<number>, 
/**
 * A sample must carry **all** of these.
 */
tags: Array<string>,
/**
 * A sample must belong to **all** of these saved collections.
 *
 * Most callers send one id: this makes a collection a browsable view of the library,
 * not a list trapped inside its management area. Keeping the same intersection
 * semantics as tags makes a future multi-collection control unsurprising.
 */
collectionIds: Array<number>,
/**
 * Lowercase, without the dot. Empty means every extension.
 */
exts: Array<string>, 
/**
 * Range constraints, one per feature. Two ranges over the same feature both apply,
 * which is a way of writing an intersection and not worth forbidding.
 */
features: Array<FeatureRange>, 
/**
 * Restrict to samples the active projection has a coordinate for.
 *
 * The renderer's filter is a mask over the point cloud, so a result containing samples
 * that are not *in* the point cloud is a result it has to filter again. Default is
 * false, because the library list is a legitimate consumer of the unfiltered form.
 */
projectedOnly: boolean, 
/**
 * Hard cap on returned ids. `None` means every match -- which is the intended case for
 * the renderer's mask, where 30,000 ids is 120 KB and the whole point of the binary
 * transport.
 */
limit?: number, };
