// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Algorithm } from "./Algorithm";

/**
 * What `start_refit` is asked for (`overview.md` §3.7, §3.8).
 */
export type RefitParams = { algorithm: Algorithm, 
/**
 * Which independently-active layout this re-fit builds: 2 or 3. The mode switcher's
 * current view, in practice -- "the map you build is the map you're looking at."
 */
dims: number, 
/**
 * UMAP's neighbourhood size. Ignored by PCA. `None` takes the vendored default.
 */
nNeighbors?: number, 
/**
 * Run a full re-fit even when the planner would have placed the new points
 * incrementally.
 *
 * The planner is right almost always -- twelve new files must not rotate a library --
 * and this exists because "almost always" is not "always": incremental placement
 * accumulates drift, and the user is the one who can see that the map has gone
 * crooked. `overview.md` §3.8 says a re-fit is announced rather than silent, and this
 * is the announcement's button.
 */
forceFull: boolean, };
