// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefitFinished } from "./RefitFinished";
import type { RefitProgressEvent } from "./RefitProgressEvent";

/**
 * What a projection re-fit streams back.
 */
export type RefitEvent = { "event": "progress" } & RefitProgressEvent | { "event": "finished" } & RefitFinished;
