// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One coalesced reading of a re-fit's counters.
 *
 * Carries `job_id` because `RefitSnapshot` does not and cannot: the `projection_runs` row
 * a re-fit ends up writing does not exist while it is fitting (`overview.md` §3.8 creates
 * the shadow run only once there are coordinates to put in it), so the id the caller was
 * given at the start is an app-assigned job id and this is where it gets attached.
 */
export type RefitProgressEvent = { jobId: number, 
/**
 * `reading` | `fitting` | `aligning` | `writing` | `swapping` | `done`. `fitting` is
 * the long one and the opaque one -- it is inside the projector, and no counter
 * crosses that boundary.
 */
phase: string, samples: number, 
/**
 * Coordinates committed to the shadow run. Zero until `writing`.
 */
written: number, };
