// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a finished re-fit produced. The terminal payload of `Channel<RefitEvent>`.
 */
export type RefitOutcome = { 
/**
 * The `projection_runs` row that is now active.
 */
runId: number, 
/**
 * The projector that actually produced the coordinates, which is not necessarily the
 * one that was asked for -- PCA is the permanent fallback.
 */
algorithm: string, sampleCount: number, 
/**
 * Samples present in both the old layout and the new one; what Procrustes was fitted
 * on.
 */
correspondences: number, 
/**
 * Median distance a pre-existing point moved, as a fraction of the cloud's diagonal.
 * `None` on a first fit. **The number `overview.md` §3.8's stability claim is about**,
 * and the reason the UI can say "the map barely moved" rather than hoping.
 */
relativeDisplacement: number | null, 
/**
 * True when the points were added to the existing layout rather than re-fitted, in
 * which case nothing that was already on the map moved at all.
 */
incremental: boolean, elapsedMs: number, };
