// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { RefitOutcome } from "./RefitOutcome";

/**
 * The terminal event of a re-fit.
 *
 * Exactly one of `outcome` and `error` is set, and `error` being `Cancelled` is the
 * ordinary case rather than a problem: a cancelled re-fit discards its shadow run and
 * leaves the map the user is looking at untouched (`overview.md` §3.8).
 */
export type RefitFinished = { jobId: number, outcome: RefitOutcome | null, error: AppError | null, };
