// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The DSP descriptor block, as the inspector renders it (`overview.md` §3.3).
 *
 * Every field is nullable because every field genuinely can be: a file that failed to
 * decode has none of them, and a pitchless sample has no key however well it decoded.
 */
export type SampleFeatureBlock = { peakDb: number | null, rmsDb: number | null, lufsIntegrated: number | null, spectralCentroid: number | null, spectralFlatness: number | null, zeroCrossing: number | null, onsetDensity: number | null, bpm: number | null, bpmConfidence: number | null, 
/**
 * 0-11, C through B. `None` for unpitched material.
 */
keyRoot: number | null, 
/**
 * 0 minor, 1 major.
 */
keyMode: number | null, keyConfidence: number | null, };
