// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SampleFeatureBlock } from "./SampleFeatureBlock";

/**
 * Everything the inspector shows for one sample.
 */
export type SampleDetail = { id: number, rootId: number, 
/**
 * Absolute path of the root, so the UI can show where a file came from without
 * concatenating paths itself.
 */
rootPath: string, relPath: string, filename: string, ext: string, sizeBytes: number, 
/**
 * Duration of the **whole** file, not of the ten-second analysis window.
 */
durationMs: number | null, sampleRate: number | null, channels: number | null, 
/**
 * `pending` | `decoded` | `embedded` | `decode_failed` | `missing`.
 */
status: string, 
/**
 * Why the file was quarantined, for a `decode_failed` row.
 */
error: string | null, 
/**
 * Whether a vector exists, which is what decides if `get_similar` can say anything.
 */
embedded: boolean, features: SampleFeatureBlock | null, tags: Array<string>, 
/**
 * Last write to this row. **The cache key for `abpeaks://`**: the peak summary of a
 * file that was rescanned after an edit is different audio at the same sample id, and
 * the scheme's `immutable` header means the WebView will never ask again on its own.
 * The frontend appends this as a query string; see `src/ipc/peaks.ts`.
 */
updatedAt: number, };
