// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stage a scan is mostly in, for a label the UI can show.
 *
 * "Mostly", because the stages overlap by design -- the walker is still finding files
 * while the embedder is running batches. The phase is the furthest stage that has started,
 * which is what a progress label is actually asking about.
 */
export type ScanPhase = "walking" | "decoding" | "embedding" | "finishing";
