// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanOutcome } from "./ScanOutcome";
import type { ScanProgress } from "./ScanProgress";

/**
 * What a scan streams back to its caller.
 */
export type ScanEvent = { "event": "progress" } & ScanProgress | { "event": "finished" } & ScanOutcome;
