// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";

/**
 * How a scan ended and what it did.
 *
 * A DTO over `db::ScanCounts` plus the counters that are not in the `scan_runs` row.
 * `status` is what the UI renders: a cancelled scan kept everything it wrote and should
 * say so, a failed one has an `error` to show, and a completed one has neither.
 */
export type ScanOutcome = { scanId: number, rootId: number, 
/**
 * `running` never appears here; the other three of [`ScanStatus`] do.
 */
status: string, filesSeen: number, filesAdded: number, filesSkipped: number, filesFailed: number, 
/**
 * Files that got a vector, whether the model ran for them or they borrowed a
 * byte-identical twin's.
 */
filesEmbedded: number, 
/**
 * Set only for `status = "failed"`, and only for a failure that stopped the scan --
 * a file that would not decode is a quarantined row, not a failed scan.
 */
error: AppError | null, };
