// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScanPhase } from "./ScanPhase";

/**
 * What one tick reports.
 *
 * The shape is `overview.md` §6.5's, which is why Phase 6 could add derives here rather
 * than a translation layer: this *is* the wire type, carried by `Channel<ScanEvent>` as
 * the `progress` variant and exported to TypeScript as `ScanProgress`. It is named
 * `ProgressSnapshot` in Rust only because [`ScanProgress`] -- the counter set -- got the
 * obvious name first.
 */
export type ScanProgress = { scanId: number, phase: ScanPhase, filesSeen: number, filesQueued: number, filesDone: number, filesSkipped: number, filesFailed: number, filesEmbedded: number, 
/**
 * Sampled, not exhaustive -- for texture, not accounting.
 */
currentPath: string | null, etaSeconds: number | null, };
