// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag, and how many samples carry it.
 */
export type Tag = { id: number, name: string, color: string | null, sampleCount: number, };
