//! `model::session` against a real ONNX Runtime.
//!
//! The real CLAP model is a 200 MB release asset that CI will never have, so without these
//! the whole of `model/session.rs` -- provider selection, the warmup, layout detection,
//! batching, extraction -- would be code that has never once met the library it wraps. The
//! graphs here are ~130 KB, generated by `scripts/make_session_fixtures.py`, and carry the
//! real export's input signature and output width. They compute nonsense, deterministically.
//!
//! **These are not the parity gate.** `tests/parity.rs` is, and it needs the real model.
//! What these prove is that the plumbing works; what that proves is that a parity failure,
//! when one happens, is a front-end bug rather than a session bug.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use audiobank_lib::{
    model::session::{ModelSession, Provider, SessionError},
    pipeline::mel::{MEL_BINS, MEL_FRAMES},
    EMBEDDING_DIM,
};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/session")
        .join(name)
}

/// The embedding the fixture graph produces for an all-zeros spectrogram, L2-normalized --
/// computed in NumPy by the generator script, so agreeing with it means the tensor went in
/// the right way round and came back out correctly.
fn silence_reference() -> Vec<f32> {
    let raw = std::fs::read(fixture("silence_embedding.f32")).unwrap();
    raw.chunks_exact(4)
        .map(|b| f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
        .collect()
}

/// A spectrogram that is different in every band and every frame, so a transposed or
/// mis-strided tensor cannot accidentally agree with a correct one.
fn ramp_mel() -> Vec<f32> {
    (0..MEL_FRAMES * MEL_BINS)
        .map(|i| {
            let (frame, mel) = (i / MEL_BINS, i % MEL_BINS);
            -40.0 + (mel as f32) * 0.7 + (frame as f32) * 0.01
        })
        .collect()
}

fn norm(v: &[f32]) -> f64 {
    v.iter()
        .map(|&x| f64::from(x) * f64::from(x))
        .sum::<f64>()
        .sqrt()
}

/// Cold path end to end: build a session, warm it up, run inference, get the right numbers.
#[test]
fn a_session_loads_warms_up_and_embeds() {
    let session = ModelSession::open(fixture("frames_major.onnx")).expect("session init failed");
    println!("bound provider: {}", session.provider().as_str());
    assert_eq!(session.embedding_dim(), EMBEDDING_DIM);

    let embedding = session.embed(&vec![0.0f32; MEL_FRAMES * MEL_BINS]).unwrap();
    assert_eq!(embedding.len(), EMBEDDING_DIM);
    assert!(
        (norm(&embedding) - 1.0).abs() < 1e-5,
        "output is not L2-normalized: |x| = {}",
        norm(&embedding)
    );

    // Against NumPy, not against itself.
    //
    // The tolerance depends on which provider bound, and that is a finding rather than a
    // fudge: **CoreML does not compute this in f32.** Measured on an M-series machine, its
    // components differ from the f64 NumPy reference by up to ~1.5e-5 where the CPU
    // provider differs by ~1e-7, which is Apple's fp16 accumulation on the ANE/GPU doing
    // exactly what it is designed to do. It matters twice over: `tests/parity.rs` compares
    // at cosine > 0.999, which this is nowhere near disturbing, and Phase 5's projection
    // must not be given a tolerance tighter than the numbers can support.
    let tolerance = match session.provider() {
        Provider::CoreMl => 1e-4,
        Provider::Cpu => 1e-6,
    };
    let reference = silence_reference();
    for (i, (&got, &want)) in embedding.iter().zip(&reference).enumerate() {
        assert!(
            (got - want).abs() < tolerance,
            "component {i}: got {got}, NumPy says {want} (provider {})",
            session.provider().as_str()
        );
    }

    // The shape of the whole vector, which no per-component tolerance can substitute for.
    let dot: f64 = embedding
        .iter()
        .zip(&reference)
        .map(|(&x, &y)| f64::from(x) * f64::from(y))
        .sum();
    assert!(
        dot > 0.99999,
        "cosine against the NumPy reference is only {dot}"
    );
}

/// **The transpose is correct.**
///
/// `overview.md` §3.4 writes the graph input as `[B, 1, 64, T]` and HTSAT's own layout is
/// `[B, 1, T, 64]`; `model::session` reads which one off the graph and transposes when it
/// has to. Feeding the same frames-major spectrogram to both graphs must produce the same
/// embedding -- if the transpose were wrong, the two would disagree, and against the real
/// model that disagreement would be invisible and would ruin every embedding in the corpus.
#[test]
fn a_mels_major_graph_gets_the_same_spectrogram_transposed() {
    let frames_major = ModelSession::open(fixture("frames_major.onnx")).unwrap();
    let mels_major = ModelSession::open(fixture("mels_major.onnx")).unwrap();

    let mel = ramp_mel();
    let a = frames_major.embed(&mel).unwrap();
    let b = mels_major.embed(&mel).unwrap();

    let worst = a
        .iter()
        .zip(&b)
        .map(|(&x, &y)| (f64::from(x) - f64::from(y)).abs())
        .fold(0.0f64, f64::max);
    // Both sessions bind the same provider, so this is a like-for-like comparison and can
    // stay tight even under CoreML's reduced precision.
    assert!(
        worst < 1e-5,
        "the two layouts disagree by {worst}; the transpose in embed_batch is wrong"
    );

    // And the input actually mattered -- otherwise the above would pass for a graph that
    // ignores its input entirely.
    let silence = frames_major
        .embed(&vec![0.0f32; MEL_FRAMES * MEL_BINS])
        .unwrap();
    assert!(
        a.iter().zip(&silence).any(|(&x, &y)| (x - y).abs() > 1e-3),
        "the fixture graph ignores its input, so this test proves nothing"
    );
}

/// A batch must be exactly the same as running its members one at a time.
///
/// Phase 4 batches 16-32 spectrograms per `run()` (`overview.md` §3.4). A batching bug that
/// smears rows into each other produces embeddings that are wrong, plausible, and
/// order-dependent.
#[test]
fn a_batch_matches_running_its_members_one_at_a_time() {
    let session = ModelSession::open(fixture("frames_major.onnx")).unwrap();

    let mels: Vec<Vec<f32>> = (0..3)
        .map(|k| ramp_mel().iter().map(|v| v + k as f32 * 3.0).collect())
        .collect();
    let flat: Vec<f32> = mels.iter().flatten().copied().collect();

    let batched = session.embed_batch(&flat, 3).unwrap();
    assert_eq!(batched.len(), 3 * EMBEDDING_DIM);

    for (k, mel) in mels.iter().enumerate() {
        let alone = session.embed(mel).unwrap();
        let row = &batched[k * EMBEDDING_DIM..(k + 1) * EMBEDDING_DIM];
        let worst = alone
            .iter()
            .zip(row)
            .map(|(&x, &y)| (f64::from(x) - f64::from(y)).abs())
            .fold(0.0f64, f64::max);
        assert!(
            worst < 1e-5,
            "batch row {k} differs from a solo run by {worst}"
        );
        assert!(
            (norm(row) - 1.0).abs() < 1e-5,
            "batch row {k} is not normalized"
        );
    }

    // Rows must be distinguishable, or the comparison above is vacuous.
    assert!(
        batched[..EMBEDDING_DIM]
            .iter()
            .zip(&batched[EMBEDDING_DIM..2 * EMBEDDING_DIM])
            .any(|(&x, &y)| (x - y).abs() > 1e-4),
        "every row of the batch is identical"
    );
}

#[test]
fn a_ragged_batch_is_refused() {
    let session = ModelSession::open(fixture("frames_major.onnx")).unwrap();
    let per_sample = MEL_FRAMES * MEL_BINS;

    assert!(matches!(
        session.embed_batch(&vec![0.0; per_sample + 1], 1),
        Err(SessionError::RaggedBatch { .. })
    ));
    assert!(matches!(
        session.embed_batch(&vec![0.0; per_sample], 0),
        Err(SessionError::RaggedBatch { .. })
    ));
    assert!(matches!(
        session.embed_batch(&vec![0.0; per_sample], 2),
        Err(SessionError::RaggedBatch { .. })
    ));
}

/// A graph that will accept the wrong number of mel bands must not load at all.
///
/// This is the interlock that turns "the export changed shape" from a corpus of silently
/// wrong embeddings into a session that refuses to start.
#[test]
fn a_graph_with_a_dynamic_mel_axis_is_rejected_at_init() {
    match ModelSession::open(fixture("dynamic_mels.onnx")) {
        Err(SessionError::NoProvider { cpu, .. }) => {
            assert!(
                cpu.contains("log-mel tensor"),
                "rejected, but not for the shape: {cpu}"
            );
        }
        Err(other) => panic!("expected a shape rejection, got {other:?}"),
        Ok(_) => panic!("a graph with a dynamic mel axis was accepted"),
    }
}

/// Phase 3's exit criterion: **both** providers initialize.
///
/// Tested through `open_on` rather than by setting `AUDIOBANK_FORCE_CPU`, because the
/// environment is process-global and the test harness is threaded -- mutating it here would
/// change what every other test in this file binds to.
#[test]
fn both_providers_initialize_and_agree() {
    let path = fixture("frames_major.onnx");
    let mel = ramp_mel();

    let cpu = ModelSession::open_on(&path, Provider::Cpu).expect("the CPU fallback is not real");
    assert_eq!(cpu.provider(), Provider::Cpu);
    let on_cpu = cpu.embed(&mel).unwrap();

    match ModelSession::open_on(&path, Provider::CoreMl) {
        Ok(coreml) => {
            assert_eq!(coreml.provider(), Provider::CoreMl);
            let on_coreml = coreml.embed(&mel).unwrap();
            let worst = on_cpu
                .iter()
                .zip(&on_coreml)
                .map(|(&x, &y)| (f64::from(x) - f64::from(y)).abs())
                .fold(0.0f64, f64::max);
            // Looser than the other comparisons on purpose: CoreML is free to reassociate
            // and to use lower intermediate precision, and it does.
            assert!(worst < 1e-3, "CoreML and CPU disagree by {worst}");
            println!("CoreML vs CPU: worst component difference {worst:.3e}");
        }
        // Not a failure. CoreML is unavailable on plenty of machines, which is the entire
        // reason the fallback exists; what must not happen is CoreML failing *silently*.
        Err(e) => println!("CoreML unavailable, CPU-only: {e}"),
    }
}

/// The lazy path: construction is free, `get` builds once, and the same `Arc` comes back.
#[test]
fn the_lazy_session_builds_once() {
    use audiobank_lib::model::session::LazySession;

    let lazy = LazySession::new(fixture("frames_major.onnx"));
    assert!(!lazy.is_initialized());

    let first = lazy.get().expect("lazy init failed");
    assert!(lazy.is_initialized());
    let second = lazy.get().unwrap();
    assert!(
        std::sync::Arc::ptr_eq(&first, &second),
        "the second get built a second session"
    );

    lazy.reset();
    assert!(!lazy.is_initialized());
}

/// The `Model` handle end to end: a verified file appears, status flips, and the lazy
/// session builds from it.
///
/// This is the composition `dev_session_info` and Phase 9's settings screen go through, and
/// it is the one path that the module-level tests each cover half of.
#[test]
fn the_model_handle_goes_from_absent_to_a_working_session() {
    use audiobank_lib::model::{Model, ModelStatus};

    let data_dir = tempfile::tempdir().unwrap();
    let model = Model::new(data_dir.path());

    // Unpinned, because no real release has been published yet -- so the first-run screen
    // has something true to say rather than an empty progress bar.
    assert_eq!(model.status(), ModelStatus::Unpinned);
    assert!(!model.session().is_initialized());

    // Stand in for a completed download. The download itself -- resume, verification,
    // atomic install -- is `model::download`'s own tests; what is being checked here is
    // that a file arriving at `paths().installed()` is all it takes for the rest to work.
    std::fs::create_dir_all(model.paths().dir()).unwrap();
    std::fs::copy(fixture("frames_major.onnx"), model.paths().installed()).unwrap();

    assert_eq!(model.status(), ModelStatus::Installed);
    let session = model.session().get().expect("session did not build");
    assert_eq!(session.embedding_dim(), EMBEDDING_DIM);
    assert!(model.session().is_initialized());

    let embedding = session.embed(&vec![0.0f32; MEL_FRAMES * MEL_BINS]).unwrap();
    assert!((norm(&embedding) - 1.0).abs() < 1e-5);
}
