//! Generates `src/pipeline/mfcc_stats.rs`: the per-dimension mean and standard deviation of
//! the raw MFCC-and-envelope features over a library, which the embedder standardizes with.
//!
//! ```text
//! cargo run --release --example mfcc_stats -- <app data dir> [output .rs file]
//! ```
//!
//! **Read-only on the app's data.** It opens `library.db` with SQLite's read-only flag and
//! does not go through `Database::open`, which would apply pending migrations to the live
//! file. It decodes every sample with the same decoder, analyzer and zero-padded mel front-end
//! a scan uses, so the statistics describe exactly the numbers the embedder will see.
//!
//! With no output path, the generated file is printed to stdout. Set `MFCC_DUMP=<file.csv>`
//! to also write every sample's raw feature vector (one row per sample, in id order), for
//! comparing against another implementation.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::print_stdout)]

use std::{fmt::Write as _, path::PathBuf};

use audiocloud_lib::pipeline::{
    decode::{BufferPool, Decoder},
    features::Analyzer,
    mel::{FrontEnd, Padding, MEL_BINS, MEL_FRAMES},
    mfcc_embed::{extract, FEATURE_DIM},
};
use rusqlite::{Connection, OpenFlags};

fn main() {
    let mut args = std::env::args().skip(1);
    let dir = PathBuf::from(
        args.next()
            .expect("usage: <app data dir> [output .rs file]"),
    );
    let out_path = args.next().map(PathBuf::from);

    let conn =
        Connection::open_with_flags(dir.join("library.db"), OpenFlags::SQLITE_OPEN_READ_ONLY)
            .expect("open library.db read-only");
    let mut roots = std::collections::HashMap::new();
    let mut stmt = conn.prepare("SELECT id, path FROM library_roots").unwrap();
    for row in stmt
        .query_map([], |r| Ok((r.get::<_, i64>(0)?, r.get::<_, String>(1)?)))
        .unwrap()
    {
        let (id, path) = row.unwrap();
        roots.insert(id, path);
    }
    let mut stmt = conn
        .prepare("SELECT root_id, rel_path, ext FROM samples WHERE status != 'missing' ORDER BY id")
        .unwrap();
    let samples: Vec<(i64, String, String)> = stmt
        .query_map([], |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)))
        .unwrap()
        .map(Result::unwrap)
        .collect();

    let mut decoder = Decoder::new(BufferPool::for_decode());
    let mut analyzer = Analyzer::new();
    let mut front_end = FrontEnd::with_padding(Padding::ZeroPad);
    let mut mel = Vec::with_capacity(MEL_FRAMES * MEL_BINS);

    let mut rows: Vec<[f32; FEATURE_DIM]> = Vec::new();
    let dump = std::env::var_os("MFCC_DUMP").map(PathBuf::from);
    let mut csv = String::new();
    let mut failed = 0usize;
    for (root_id, rel_path, ext) in &samples {
        let path = PathBuf::from(&roots[root_id]).join(rel_path);
        match decoder.decode(&path, ext) {
            Ok(decoded) => {
                front_end.compute(&decoded.samples, &mut analyzer, &mut mel);
                let raw = extract(&decoded.samples, &mel, decoded.truncated);
                if dump.is_some() {
                    let cells: Vec<String> = raw.iter().map(|v| format!("{v}")).collect();
                    writeln!(csv, "{rel_path},{}", cells.join(",")).unwrap();
                }
                rows.push(raw);
            }
            Err(_) => failed += 1,
        }
    }
    assert!(rows.len() >= 2, "need at least two decodable samples");
    eprintln!(
        "{} samples featurized, {failed} failed to decode",
        rows.len()
    );
    if let Some(path) = dump {
        std::fs::write(path, csv).expect("write dump");
    }

    let n = rows.len() as f64;
    let mut mean = [0.0f32; FEATURE_DIM];
    let mut std = [1.0f32; FEATURE_DIM];
    for d in 0..FEATURE_DIM {
        let m = rows.iter().map(|r| f64::from(r[d])).sum::<f64>() / n;
        let var = rows
            .iter()
            .map(|r| (f64::from(r[d]) - m).powi(2))
            .sum::<f64>()
            / n;
        mean[d] = m as f32;
        // A dimension that never varies (a library of one-shots has no capped sounds) has
        // nothing to standardize; 1.0 leaves it as a constant offset from the mean.
        std[d] = if var.sqrt() > 1e-6 {
            var.sqrt() as f32
        } else {
            1.0
        };
    }

    let mut out = String::new();
    out.push_str(
        "//! Corpus statistics for standardizing raw features into the stored vector\n\
         //! ([`super::mfcc_embed::standardize`]).\n\
         //!\n\
         //! Generated by `cargo run --release --example mfcc_stats -- <app data dir> <this file>`;\n\
         //! do not edit by hand. Changing these changes every stored vector's meaning, so a\n\
         //! change needs a `V*__reembed_*.sql` migration that sends embedded rows back to\n\
         //! `decoded`.\n\n",
    );
    for (name, values) in [("MEAN", &mean), ("STD", &std)] {
        writeln!(out, "#[rustfmt::skip]").unwrap();
        writeln!(
            out,
            "pub const {name}: [f32; super::mfcc_embed::FEATURE_DIM] = ["
        )
        .unwrap();
        for chunk in values.chunks(5) {
            let line: Vec<String> = chunk.iter().map(|v| format!("{v:?}")).collect();
            writeln!(out, "    {},", line.join(", ")).unwrap();
        }
        out.push_str("];\n\n");
    }
    let out = out.trim_end().to_string() + "\n";

    match out_path {
        Some(path) => std::fs::write(path, out).expect("write output"),
        None => print!("{out}"),
    }
}
